import '../models/car_model.dart';
import '../models/booking_model.dart';
import '../models/offer_model.dart';
import '../models/chat_message_model.dart';
import '../models/user_model.dart';

class DummyDataSeeder {
  static List<CarModel> get initialCars => [
    CarModel(
      id: 'car_bmw_m4',
      title: '2024 BMW M4 Competition Coupe',
      make: 'BMW',
      model: 'M4 Competition',
      year: 2024,
      price: 84900,
      emi: 1180,
      mileage: 4100,
      bodyStyle: 'Coupe',
      fuelType: 'Petrol',
      transmission: 'Automatic',
      horsePower: 503,
      acceleration: '3.8s (0-60)',
      topSpeed: '180 mph',
      location: 'Los Angeles, CA',
      images: [
        'https://images.unsplash.com/photo-1617814076367-b759c7d7e738?auto=format&fit=crop&w=1200&q=80',
        'https://images.unsplash.com/photo-1555215695-3004980ad54e?auto=format&fit=crop&w=1200&q=80',
        'https://images.unsplash.com/photo-1580273916550-e323be2ae537?auto=format&fit=crop&w=1200&q=80',
      ],
      isCertified: true,
      inspectionScore: 99,
      sellerName: 'AutoElite Certified Dealership',
      sellerType: 'Certified Dealer',
      sellerRating: 4.9,
      sellerPhone: '+1 (310) 555-0199',
      vin: 'WBA33AY08PFP99182',
      isFeatured: true,
      inspectionHighlights: [
        '150-Point Technical Certification Approved',
        'TwinPower Turbo S58 Engine Performance Verified',
        'Original M Carbon Bucket Seats Flawless',
        'Zero Accident Records & Clean CarFax',
      ],
    ),
    CarModel(
      id: 'car_porsche_911',
      title: '2023 Porsche 911 Carrera S',
      make: 'Porsche',
      model: '911 Carrera S',
      year: 2023,
      price: 128500,
      emi: 1780,
      mileage: 8900,
      bodyStyle: 'Coupe',
      fuelType: 'Petrol',
      transmission: 'PDK Automatic',
      horsePower: 443,
      acceleration: '3.5s (0-60)',
      topSpeed: '191 mph',
      location: 'Beverly Hills, CA',
      images: [
        'https://images.unsplash.com/photo-1503376780353-7e6692767b70?auto=format&fit=crop&w=1200&q=80',
        'https://images.unsplash.com/photo-1614162692292-7ac56d7f7f1e?auto=format&fit=crop&w=1200&q=80',
      ],
      isCertified: true,
      inspectionScore: 98,
      sellerName: 'Beverly Hills Motors',
      sellerType: 'Premier Dealer',
      sellerRating: 5.0,
      sellerPhone: '+1 (310) 902-3341',
      vin: 'WP0AB2A99PS182736',
      isFeatured: true,
    ),
    CarModel(
      id: 'car_amg_gt',
      title: '2024 Mercedes-AMG GT 63 S E-Performance',
      make: 'Mercedes-Benz',
      model: 'AMG GT 63 S',
      year: 2024,
      price: 162000,
      emi: 2250,
      mileage: 2300,
      bodyStyle: 'Sedan',
      fuelType: 'Hybrid',
      transmission: 'Automatic',
      horsePower: 630,
      acceleration: '3.1s (0-60)',
      topSpeed: '196 mph',
      location: 'Newport Beach, CA',
      images: [
        'https://images.unsplash.com/photo-1618843479313-40f8afb4b4d8?auto=format&fit=crop&w=1200&q=80',
        'https://images.unsplash.com/photo-1605559424843-9e4c228bf1c2?auto=format&fit=crop&w=1200&q=80',
      ],
      isCertified: true,
      inspectionScore: 100,
      sellerName: 'Mercedes-Benz of South Coast',
      sellerType: 'Certified Dealer',
      sellerRating: 4.8,
      vin: 'WDD2906891A992812',
      isFeatured: true,
    ),
    CarModel(
      id: 'car_audi_rs7',
      title: '2023 Audi RS7 Sportback Performance',
      make: 'Audi',
      model: 'RS7 Sportback',
      year: 2023,
      price: 119800,
      emi: 1660,
      mileage: 11200,
      bodyStyle: 'Sedan',
      fuelType: 'Petrol',
      transmission: 'Tiptronic',
      horsePower: 591,
      acceleration: '3.5s (0-60)',
      topSpeed: '190 mph',
      location: 'Santa Monica, CA',
      images: [
        'https://images.unsplash.com/photo-1606664515524-ed2f786a0bd6?auto=format&fit=crop&w=1200&q=80',
        'https://images.unsplash.com/photo-1603584173870-7f23fdae1b7a?auto=format&fit=crop&w=1200&q=80',
      ],
      isCertified: true,
      inspectionScore: 97,
      sellerName: 'Westside Prestige Exotics',
      sellerType: 'Certified Dealer',
      sellerRating: 4.7,
      vin: 'WAUZZZF27PN099182',
    ),
    CarModel(
      id: 'car_tesla_plaid',
      title: '2024 Tesla Model S Plaid AWD',
      make: 'Tesla',
      model: 'Model S Plaid',
      year: 2024,
      price: 89990,
      emi: 1250,
      mileage: 3400,
      bodyStyle: 'Sedan',
      fuelType: 'Electric',
      transmission: 'Single-Speed',
      horsePower: 1020,
      acceleration: '1.99s (0-60)',
      topSpeed: '200 mph',
      location: 'Pasadena, CA',
      images: [
        'https://images.unsplash.com/photo-1560958089-b8a1929cea89?auto=format&fit=crop&w=1200&q=80',
        'https://images.unsplash.com/photo-1536700503339-1e4b06520771?auto=format&fit=crop&w=1200&q=80',
      ],
      isCertified: true,
      inspectionScore: 99,
      sellerName: 'Pacific EV Collective',
      sellerType: 'Dealer',
      sellerRating: 4.9,
      vin: '5YJSA1E67PF182903',
    ),
    CarModel(
      id: 'car_bmw_x5m',
      title: '2023 BMW X5 M Competition',
      make: 'BMW',
      model: 'X5 M Competition',
      year: 2023,
      price: 114200,
      emi: 1590,
      mileage: 14800,
      bodyStyle: 'SUV',
      fuelType: 'Petrol',
      transmission: 'M Steptronic',
      horsePower: 617,
      acceleration: '3.7s (0-60)',
      topSpeed: '177 mph',
      location: 'Irvine, CA',
      images: [
        'https://images.unsplash.com/photo-1549399542-7e3f8b79c341?auto=format&fit=crop&w=1200&q=80',
        'https://images.unsplash.com/photo-1552519507-da3b142c6e3d?auto=format&fit=crop&w=1200&q=80',
      ],
      isCertified: true,
      inspectionScore: 96,
      sellerName: 'AutoElite Certified Dealership',
      sellerType: 'Certified Dealer',
      sellerRating: 4.9,
      vin: '5YMJU0C08P9928172',
    ),
    CarModel(
      id: 'car_corvette_z06',
      title: '2023 Chevrolet Corvette Z06 3LZ Convertible',
      make: 'Chevrolet',
      model: 'Corvette Z06',
      year: 2023,
      price: 132000,
      emi: 1830,
      mileage: 5600,
      bodyStyle: 'Convertible',
      fuelType: 'Petrol',
      transmission: 'Dual-Clutch 8-Speed',
      horsePower: 670,
      acceleration: '2.6s (0-60)',
      topSpeed: '195 mph',
      location: 'Anaheim, CA',
      images: [
        'https://images.unsplash.com/photo-1552519507-da3b142c6e3d?auto=format&fit=crop&w=1200&q=80',
        'https://images.unsplash.com/photo-1503376780353-7e6692767b70?auto=format&fit=crop&w=1200&q=80',
      ],
      isCertified: true,
      inspectionScore: 98,
      sellerName: 'Heritage Muscle & Exotics',
      sellerType: 'Dealer',
      sellerRating: 4.6,
      vin: '1G1YB2D33P5109827',
    ),
  ];

  static UserModel get defaultBuyer => UserModel(
    uid: 'user_alex_mitchell',
    email: 'alex.mitchell@luxurymail.com',
    name: 'Alex Mitchell',
    phone: '+1 (310) 982-1204',
    avatarUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuAkCU3NRWMnIYDeXqQb9qNBpB3BjjHbr4b8O-QC1vnmM4Iz0DgaFt6ggh8pV5_KfnCDeykpvCZ4gZqShJJd31LtajaZ5BAljWYu4GAp-KW5zYvzI3t3K0qi3Jx97eWMUKcAGsYSKepdcmJWErUjCAwANqbRg8kpCOOsCpeRkAaH7pemF8apGorbcNzUdY_vZkRhf0w7GCPb9-qx5yWTBBexJqziKy9lleFbuwjuQaAhVn9qMf6xBFNa',
    role: 'Buyer',
    kycStatus: 'Tier 2 Verified',
    savedCarsCount: 3,
    activeBookingsCount: 1,
  );

  static List<BookingModel> get initialBookings => [
    BookingModel(
      id: 'booking_01',
      carId: 'car_bmw_m4',
      carTitle: '2024 BMW M4 Competition Coupe',
      carImage: 'https://images.unsplash.com/photo-1617814076367-b759c7d7e738?auto=format&fit=crop&w=1200&q=80',
      carPrice: 84900,
      buyerName: 'Alex Mitchell',
      buyerPhone: '+1 (310) 982-1204',
      buyerEmail: 'alex.mitchell@luxurymail.com',
      date: 'Tomorrow, 10:30 AM',
      timeSlot: '10:30 AM - 11:30 AM',
      deliveryType: 'Dealership VIP Showroom',
      address: '9440 Wilshire Blvd, Beverly Hills, CA',
      status: 'Confirmed',
      createdAt: DateTime.now().subtract(const Duration(hours: 4)),
    ),
  ];

  static List<OfferModel> get initialOffers => [
    OfferModel(
      id: 'offer_01',
      carId: 'car_bmw_m4',
      carTitle: '2024 BMW M4 Competition Coupe',
      listedPrice: 84900,
      offerAmount: 81500,
      counterAmount: 82900,
      buyerId: 'user_alex_mitchell',
      buyerName: 'Alex Mitchell',
      sellerId: 'dealer_autoelite',
      status: 'Countered',
      updatedAt: DateTime.now().subtract(const Duration(minutes: 45)),
    ),
  ];

  static List<ChatMessageModel> get initialChatMessages => [
    ChatMessageModel(
      id: 'msg_01',
      senderId: 'user_alex_mitchell',
      senderName: 'Alex Mitchell',
      text: 'Hi! Is this BMW M4 Competition still available for a weekend test drive?',
      isFromBuyer: true,
      timestamp: DateTime.now().subtract(const Duration(minutes: 90)),
    ),
    ChatMessageModel(
      id: 'msg_02',
      senderId: 'dealer_autoelite',
      senderName: 'Marcus Vance (AutoElite)',
      text: 'Hello Alex! Yes, it is in our showroom right now. All 150 inspection points passed with a 99 score.',
      isFromBuyer: false,
      timestamp: DateTime.now().subtract(const Duration(minutes: 80)),
    ),
    ChatMessageModel(
      id: 'msg_03',
      senderId: 'user_alex_mitchell',
      senderName: 'Alex Mitchell',
      text: 'I submitted an offer of \$81,500. Can we close the deal today?',
      isFromBuyer: true,
      timestamp: DateTime.now().subtract(const Duration(minutes: 50)),
      isSystemOffer: true,
      offerAmount: 81500,
    ),
    ChatMessageModel(
      id: 'msg_04',
      senderId: 'dealer_autoelite',
      senderName: 'Marcus Vance (AutoElite)',
      text: 'We reviewed your offer with management. We can meet you in the middle at \$82,900 inclusive of certified delivery!',
      isFromBuyer: false,
      timestamp: DateTime.now().subtract(const Duration(minutes: 40)),
      isSystemOffer: true,
      offerAmount: 82900,
    ),
  ];
}
